In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
hrt=pd.read_csv("heart.csv")

In [3]:
hrt


age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [4]:
hrt.describe()

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [5]:
hrt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
hrt['cp']

0      3
1      2
2      1
3      1
4      0
      ..
298    0
299    3
300    0
301    0
302    1
Name: cp, Length: 303, dtype: int64

In [7]:
from sklearn import preprocessing

In [8]:
h=preprocessing.StandardScaler().fit_transform(hrt)

In [9]:
h

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -0.71442887,
        -2.14887271,  0.91452919],
       [-1.91531289,  0.68100522,  1.00257707, ..., -0.71442887,
        -0.51292188,  0.91452919],
       [-1.47415758, -1.46841752,  0.03203122, ..., -0.71442887,
        -0.51292188,  0.91452919],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ...,  1.24459328,
         1.12302895, -1.09345881],
       [ 0.29046364,  0.68100522, -0.93851463, ...,  0.26508221,
         1.12302895, -1.09345881],
       [ 0.29046364, -1.46841752,  0.03203122, ...,  0.26508221,
        -0.51292188, -1.09345881]])

In [10]:
h[0]

array([ 0.9521966 ,  0.68100522,  1.97312292,  0.76395577, -0.25633371,
        2.394438  , -1.00583187,  0.01544279, -0.69663055,  1.08733806,
       -2.27457861, -0.71442887, -2.14887271,  0.91452919])

In [11]:
from sklearn.model_selection import train_test_split

In [52]:
ht=h.iloc[:,-1]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [13]:
ht

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [38]:
hrt_train,hrt_test,ht_train,ht_test=train_test_split(hrt,ht,test_size=0.3,random_state=1)

In [39]:
ht_test.shape

(91,)

In [40]:
hrt['output'].value_counts()

1    165
0    138
Name: output, dtype: int64

In [41]:
ht_test

204    0
159    1
219    0
174    0
184    0
      ..
106    1
105    1
67     1
291    0
247    0
Name: output, Length: 91, dtype: int64

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knnhrt=KNeighborsClassifier(n_neighbors=3)

In [20]:
knnhrt.fit(hrt_train,ht_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [21]:
ht_predict=knnhrt.predict(hrt_test)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy=accuracy_score(ht_test,ht_predict)

In [34]:
accuracy

0.6263736263736264

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
conmat=confusion_matrix(ht_test,ht_predict)

In [ ]:
conmat

In [ ]:
conmat1=pd.DataFrame(data=conmat,index=['1','0'],columns=['1','0'])

In [ ]:
conmat1

In [ ]:
pred_op=pd.DataFrame(data=[ht_test.values,ht_predict],index=['ht_test','ht_predict'])

In [ ]:
pred_op

In [ ]:
pred_op.transpose()

In [ ]:
ks=21
mean_acc=np.zeros((ks-1))

In [ ]:
mean_acc

In [ ]:
for i in range(1,ks):
    neigh=KNeighborsClassifier(n_neighbors=i).fit(hrt_train,ht_train)
    zhat=neigh.predict(hrt_test)
    mean_acc[i-1]=accuracy_score(ht_test,zhat)

In [ ]:
print("the best accuracy is {} and with k= {}".format(mean_acc.max(),mean_acc.argmax()+1))

In [ ]:
plt.plot(range(1,ks),mean_acc,'r')

In [ ]:
plt.plot(range(1,ks),mean_acc,'r')
plt.ylabel("Accuracy")
plt.xlabel('k')
plt.tight_layout()
plt.show()

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [43]:
lm=LinearRegression()

In [44]:
lm.fit(hrt_train,ht_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [45]:
r_sc=lm.score(hrt_train,ht_train)

In [46]:
r_sc

1.0

In [47]:
incp=lm.intercept_

In [48]:
incp

2.0317081350640365e-14

In [49]:
lm.coef_

array([-3.98377523e-16,  4.14167144e-16, -4.58027422e-18,  6.65461673e-17,
        1.07672705e-17,  2.14826799e-16, -1.82851899e-17, -6.85150278e-17,
        1.90977488e-17, -2.46603069e-16, -7.17774671e-17, -9.05075503e-18,
        6.97247404e-17,  1.00000000e+00])

In [50]:
lm_ht_predict=lm.predict(hrt_test)

In [53]:
lm_ht_predict

array([-3.25070206e-15,  1.00000000e+00,  3.02073854e-15, -1.79978147e-15,
        4.13704938e-15, -3.82255321e-15,  3.11173249e-15,  1.00000000e+00,
       -7.67067904e-16,  1.00000000e+00,  1.00000000e+00, -5.10076673e-15,
       -5.30021613e-16, -2.40986089e-15,  1.28654054e-15, -3.06593373e-15,
        1.00000000e+00, -1.84398049e-15,  1.00000000e+00,  8.21242871e-16,
        1.00000000e+00, -4.88092428e-15,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00, -9.19661162e-16,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  3.85013277e-15,  1.00000000e+00,
        1.00000000e+00, -5.80832123e-15,  2.81006387e-15,  1.00000000e+00,
        1.00000000e+00,  3.92505366e-17,  1.00000000e+00,  4.74423370e-15,
       -3.65738478e-15, -3.36289170e-15, -1.57768940e-16,  1.00000000e+00,
        4.95838039e-15,  1.00000000e+00,  1.00000000e+00,  1.42259867e-15,
        3.73236116e-15,  